# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build project

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Build project
      run: yarn build
    - name: Run unit test
      run: yarn test
    - name: Run integration tests
      run: yarn test:e2e
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()  
      with:
        name: Junit            # Name of the check run which will be created
        path: reports/**.xml    # Path to test results
        reporter: jest-junit        # Format of test results
